flowchart TD
	A[Inicio] --> B[Inicializar]
	B --> C[Para dia=1..7]
	C --> D[Leer cantidad]
	D --> E[Acumular total]
	E --> F{cantidad<20}
	F -- Sí --> G[cont_inferior_20++]
	F -- No --> H[--]
	G --> I{cantidad<10}
	H --> I
	I -- Sí --> J[Mostrar ALERTA]
	I -- No --> K[--]
	K --> L{cantidad > mayor_cantidad}
	L -- Sí --> M[Actualizar mayor_cantidad y dia_mayor]
	L -- No --> N[--]
	N --> O[Fin Para]
	O --> P[Calcular promedio y Mostrar resultados]
	P --> Q[Fin]
